/**
 * Daily Settlement Batch Cron Job
 * Route: GET /api/cron/settlement
 * Runs daily at 23:00 to create settlement batches using the canonical
 * BankServ settlement path (bankserv_adaptor_transactions + billing_settlement_batches).
 *
 * Vercel Cron: Configured in vercel.json:
 * {
 *   "crons": [{
 *     "path": "/api/cron/settlement",
 *     "schedule": "0 23 * * *"
 *   }]
 * }
 */

import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { writeAuditEvent } from '@/server/utils/audit';

const CRON_SECRET = process.env.CRON_SECRET || 'dev-cron-secret';

function buildBatchNumber() {
  const now = new Date();
  const stamp = now.toISOString().slice(0, 10).replace(/-/g, '');
  const suffix = Math.random().toString(36).slice(2, 6).toUpperCase();
  return `BATCH-${stamp}-${suffix}`;
}

export async function GET(request: NextRequest) {
  try {
    // 1. Verify cron secret
    const authHeader = request.headers.get('authorization');
    if (authHeader !== `Bearer ${CRON_SECRET}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    console.log('[Settlement Cron] Starting daily settlement batch job...');

    const admin = createAdminClient();

    // 2. Query pending merchant payouts (canonical path)
    const { data: payouts, error: payoutsError } = await admin
      .from('merchant_payouts')
      .select('id,merchant_id,amount,status,created_at')
      .eq('status', 'pending');

    if (payoutsError) {
      console.error('[Settlement Cron] Failed to query payouts:', payoutsError.message);
      throw payoutsError;
    }

    if (!payouts || payouts.length === 0) {
      console.log('[Settlement Cron] No pending payouts ready for settlement');
      return NextResponse.json({
        success: true,
        message: 'No pending payouts ready for settlement',
        timestamp: new Date().toISOString(),
      });
    }

    // 3. Resolve merchant banking details
    const merchantIds = Array.from(new Set(payouts.map((p) => p.merchant_id)));
    const { data: merchants, error: merchantsError } = await admin
      .from('merchants')
      .select('id,business_name,bank_name,branch_code,account_number,contact_name')
      .in('id', merchantIds);

    if (merchantsError) throw merchantsError;
    const merchantMap = new Map((merchants ?? []).map((m) => [m.id, m]));

    const payoutTotals = new Map<string, number>();
    payouts.forEach((row) => {
      const merchantId = String(row.merchant_id);
      const next = Number(row.amount ?? 0);
      payoutTotals.set(merchantId, (payoutTotals.get(merchantId) ?? 0) + next);
    });

    // 4. Create settlement batch
    const batchNumber = buildBatchNumber();
    const totalAmount = Array.from(payoutTotals.values()).reduce((sum, value) => sum + value, 0);

    const { data: batch, error: batchError } = await admin
      .from('billing_settlement_batches')
      .insert({
        batch_number: batchNumber,
        status: 'pending_approval',
        total_amount: Number(totalAmount.toFixed(2)),
        merchant_count: payoutTotals.size,
        transaction_count: payouts.length,
        created_by: 'system_cron',
        notes: 'Auto-generated by daily settlement cron',
      })
      .select('*')
      .single();

    if (batchError || !batch) throw batchError ?? new Error('Failed to create batch.');

    console.log('[Settlement Cron] Batch created:', batchNumber);

    // 5. Create billing_settlements rows
    const settlementRows = Array.from(payoutTotals.entries()).map(([merchantId, amount]) => {
      const merchant = merchantMap.get(merchantId);
      return {
        batch_id: batch.id,
        merchant_id: merchantId,
        amount: Number(amount.toFixed(2)),
        bank_name: merchant?.bank_name ?? null,
        branch_code: merchant?.branch_code ?? null,
        account_number: merchant?.account_number ?? null,
        account_holder: merchant?.contact_name ?? merchant?.business_name ?? null,
        reference: `${batch.batch_number}-${merchant?.business_name ?? merchantId}`.slice(0, 64),
        status: 'pending',
      };
    });

    if (settlementRows.length > 0) {
      const { error: settlementError } = await admin
        .from('billing_settlements')
        .insert(settlementRows);
      if (settlementError) throw settlementError;
    }

    // 6. Update merchant_payouts status to batched
    const payoutIds = payouts.map((row) => row.id);
    if (payoutIds.length > 0) {
      const { error: payoutUpdateError } = await admin
        .from('merchant_payouts')
        .update({ status: 'batched' })
        .in('id', payoutIds);
      if (payoutUpdateError) throw payoutUpdateError;
    }

    // 7. Update bankserv_adaptor_transactions with batch_id
    const { error: adaptorUpdateError } = await admin
      .from('bankserv_adaptor_transactions')
      .update({ status: 'batched', batch_id: batch.id })
      .in('merchant_id', merchantIds)
      .eq('status', 'queued');
    if (adaptorUpdateError) {
      console.warn('[Settlement Cron] Failed to update adaptor transactions:', adaptorUpdateError.message);
    }

    // 8. Audit log
    try {
      await writeAuditEvent(admin, {
        actorId: 'system_cron',
        actorRole: 'system',
        entityType: 'billing_settlement_batch',
        entityId: batch.id,
        action: 'settlement_batch_cron_created',
        metadata: {
          batchNumber: batch.batch_number,
          totalAmount: batch.total_amount,
          merchantCount: batch.merchant_count,
          payoutCount: payouts.length,
        },
        requestId: batch.batch_number,
      });
    } catch (auditError: any) {
      console.warn('[Settlement Cron][audit][warn]', auditError?.message || auditError);
    }

    return NextResponse.json({
      success: true,
      message: 'Settlement batch created via canonical path.',
      batchId: batch.id,
      batchReference: batch.batch_number,
      settlementsCreated: settlementRows.length,
      payoutsBatched: payouts.length,
      timestamp: new Date().toISOString(),
    });
  } catch (error: any) {
    console.error('[Settlement Cron] Job failed:', error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || 'Settlement batch job failed',
        timestamp: new Date().toISOString(),
      },
      { status: 500 }
    );
  }
}

// Manual trigger endpoint (for testing)
export async function POST(request: NextRequest) {
  return GET(request);
}